### PR TITLE
Fix whitelist matching issues

### LINKED ISSUE #93: no heartbeat
Is it possible that this extension may not work when you select the "whitelist" mode?

I see coding data but no browsing data on https://wakatime.com/api/v1/users/current/heartbeats?date=2020-11-24&show=machine_name,user_agent.

### Extensions options

image

### Installed plugins

image

### PR DESCRIPTION
**Pull request by cilerler**
This PR will add features below and closes #93

- ignore trailing `/` or `@@`
- ignore the `http://` or `https://` prefixes on whitelisted URLs
- ignore case sensitivity in URL

### CODE REVIEW

File: assets/js/core/WakaTimeCore.js [hunk 1]
```diff
@@ -146,35 +146,46 @@ class WakaTimeCore {
...
-                        url: cleanLine.split('@@')[0],
-                        project: null,
-                    };
-                }
-            }
+        for (var i = 0; i < lines.length; i++) {
+          // strip (http:// or https://) and trailing (`/` or `@@`)
+          var line = lines[i];
+          var cleanLine = line.trim().replace(/(\/|@@)$/, '').replace(/^(?:https?:\/\/)?/i, '');
+          var emptyLine = cleanLine === '';
```
Comment (alanhamlett) [inline assets/js/core/WakaTimeCore.js:153]: nit: this var only used once, so it should be inlined in the conditional below.

**Review by alanhamlett — APPROVED** [review]
